package com.hs.modelo;
// Generated 28/05/2018 17:37:41 by Hibernate Tools 4.3.1


import java.util.Date;
/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {
     private int idUsu;
     private String nombreUsu;
     private String apellidoUsu;
     private Long dniUsu;     
     private String passUsu;
     private String mailUsu;
     private String direccionUsu;
     private String entreCalle1Usu;
     private String entreCalle2Usu;
     private Integer numeroUsu;
     private Integer pisoUsu;
     private String departamentoUsu;
     private String localidadUsu;
     private Integer codposUsu;
     private Date ultimoAccesoUsu;

    public Usuarios() {
    }

	
    public Usuarios(int idUsu) {
        this.idUsu = idUsu;
    }
    public Usuarios(int idUsu, 
                 String nombreUsu, 
                 String apellidoUsu, 
                 Long dniUsu, 
                 String passUsu, 
                 String mailUsu, 
                 String direccionUsu, 
                 String entreCalle1Usu, 
                 String entreCalle2Usu, 
                 Integer numeroUsu, 
                 Integer pisoUsu, 
                 String departamentoUsu, 
                 String localidadUsu, 
                 Integer codposUsu, 
                 Date ultimoAccesoUsu) {
       this.idUsu = idUsu;
       this.nombreUsu = nombreUsu;
       this.apellidoUsu = apellidoUsu;
       this.dniUsu = dniUsu;
       this.passUsu = passUsu;
       this.mailUsu = mailUsu;
       this.direccionUsu = direccionUsu;
       this.entreCalle1Usu = entreCalle1Usu;
       this.entreCalle2Usu = entreCalle2Usu;
       this.numeroUsu = numeroUsu;
       this.pisoUsu = pisoUsu;
       this.departamentoUsu = departamentoUsu;
       this.localidadUsu = localidadUsu;
       this.codposUsu = codposUsu;
       this.ultimoAccesoUsu = ultimoAccesoUsu;
    }
   
    public int getIdUsu() {
        return this.idUsu;
    }
    
    public void setIdUsu(int idUsu) {
        this.idUsu = idUsu;
    }
    public String getNombreUsu() {
        return this.nombreUsu;
    }
    
    public void setNombreUsu(String nombreUsu) {
        this.nombreUsu = nombreUsu;
    }
    public String getApellidoUsu() {
        return this.apellidoUsu;
    }
    
    public void setApellidoUsu(String apellidoUsu) {
        this.apellidoUsu = apellidoUsu;
    }
    public Long getDniUsu() {
        return this.dniUsu;
    }
    
    public void setDniUsu(Long dniUsu) {
        this.dniUsu = dniUsu;
    }
    public String getPassUsu() {
        return this.passUsu;
    }
    
    public void setPassUsu(String passUsu) {
        this.passUsu = passUsu;
    }
    public String getMailUsu() {
        return this.mailUsu;
    }
    
    public void setMailUsu(String mailUsu) {
        this.mailUsu = mailUsu;
    }
    public String getDireccionUsu() {
        return this.direccionUsu;
    }
    
    public void setDireccionUsu(String direccionUsu) {
        this.direccionUsu = direccionUsu;
    }
    public String getEntreCalle1Usu() {
        return this.entreCalle1Usu;
    }
    
    public void setEntreCalle1Usu(String entreCalle1Usu) {
        this.entreCalle1Usu = entreCalle1Usu;
    }
    public String getEntreCalle2Usu() {
        return this.entreCalle2Usu;
    }
    
    public void setEntreCalle2Usu(String entreCalle2Usu) {
        this.entreCalle2Usu = entreCalle2Usu;
    }
    public Integer getNumeroUsu() {
        return this.numeroUsu;
    }
    
    public void setNumeroUsu(Integer numeroUsu) {
        this.numeroUsu = numeroUsu;
    }
    public Integer getPisoUsu() {
        return this.pisoUsu;
    }
    
    public void setPisoUsu(Integer pisoUsu) {
        this.pisoUsu = pisoUsu;
    }
    public String getDepartamentoUsu() {
        return this.departamentoUsu;
    }
    
    public void setDepartamentoUsu(String departamentoUsu) {
        this.departamentoUsu = departamentoUsu;
    }
    public String getLocalidadUsu() {
        return this.localidadUsu;
    }
    
    public void setLocalidadUsu(String localidadUsu) {
        this.localidadUsu = localidadUsu;
    }
    public Integer getCodposUsu() {
        return this.codposUsu;
    }
    
    public void setCodposUsu(Integer codposUsu) {
        this.codposUsu = codposUsu;
    }
    public Date getUltimoAccesoUsu() {
        return this.ultimoAccesoUsu;
    }
    
    public void setUltimoAccesoUsu(Date ultimoAccesoUsu) {
        this.ultimoAccesoUsu = ultimoAccesoUsu;
    }




}


